Add GGJ22 info
lithekod/site-v2 pull request #113
Opened 2022-01-12 19:48 UTC by axerosh

Updates the game jam pages with information for Global Game Jam 2022, including a new GGJ22 banner.

Preview of the updated banner:
![image](https://user-images.githubusercontent.com/1302408/149210956-bcbe9734-4a1a-471e-908c-aff71e19a168.png)

2022-01-13 07:55 UTC, JesperTingvall requested changes

2022-01-13 07:55 UTC, JesperTingvall commented on website/pages/gamejam_en.md
> +- 23:00
Nightchill will start 22:00 according to feedback.

2022-01-13 07:55 UTC, JesperTingvall commented on website/pages/gamejam_se.md
> +- 23:00
Nightchill will start 22:00 according to feedback.

2022-01-16 09:59 UTC, vollells approved these changes

2022-01-16 10:00 UTC, FredTheDino approved these changes
Very fine!

2022-01-17 15:15 UTC, merged