Git???
lithekod/site-v2 pull request #48
Opened 2021-01-11 17:36 UTC by FredTheDino

Gjorde en sida vi kan länka till om Git-föreläsningen.

2021-01-12 09:42 UTC, EMattfolk requested changes
Det var en del saker som jag tycker borde ändras. Men jag måste ändå säga att det har blivit enkelt att lägga till sidor.

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_en.md
> +a git workshop on Zoom! To get there, simple visit this page on the 3rd of februari at 17:30.
```suggestion
a git workshop on Zoom! To get there, simply visit this page on the 3rd of february at 5:30pm.
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_en.md
> +The 3rd of February 17:30-19:00 LiTHe-kod will be hosting
```suggestion
The 3rd of February 5:30pm to 7:00pm LiTHe-kod will be hosting
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_en.md
> +You will be redirected using the magic of the internets and arrive at stimulating Zoom-meeting.
```suggestion
You will be redirected using the magic of the internet and arrive at a stimulating Zoom-meeting.
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_en.md
> +The workshop consists of 2 parts. One theoretical part, a lecture for ~45 minutes where
```suggestion
The workshop consists of 2 parts. One theoretical part: a lecture for ~45 minutes where
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_en.md
> +exercises where you can apply the lecture on smaller exercises. We will ofcourse be present
```suggestion
exercises where you can apply your new skills. We will be present
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_se.md
> +Bokmarkera denna sida och skriv ner datumet i din kalender! Ses där.
```suggestion
Bokmärk denna sida och skriv ner datumet i din kalender! Ses där.
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_se.md
> +# git-workshop
```suggestion
# git-workshop

```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_en.md
> +# git Workshop
```suggestion
# git Workshop

```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_se.md
> +Dags att vässa ditt CV, skaffa kompetenser som bara fortsätter att ge och ha en
```suggestion
Dags att vässa ditt CV, lära sig användbara kompetenser och ha en
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_se.md
> +Workshoppen består av två delar. En teoretisk bit i form av föreläsning på ~45 minuter där
```suggestion
Workshoppen består av två delar. En teoretisk del i form av föreläsning på ~45 minuter där
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_se.md
> +kommandon och teori gås igenom och man kan fråga frågor. Efter föreläsning kommer
```suggestion
kommandon och teori gås igenom. Under föreläsningen går det
även bra att ställa frågor. Efter föreläsning kommer
```

2021-01-12 09:42 UTC, EMattfolk commented on website/pages/git_se.md
> +den interaktiva biten av workshoppen där vi kommer ge ut "git-uppgifter" som ni
```suggestion
den interaktiva delen av workshoppen där vi kommer ge ut "git-uppgifter" som ni
```

2021-01-12 11:12 UTC, th3tard1sparadox requested changes

2021-01-12 11:12 UTC, th3tard1sparadox commented on website/pages/git_en.md
> +a git workshop on Zoom! To get there, simple visit this page on the 3rd of februari at 17:30.
```suggestion
a git workshop on Zoom! To get there, simply visit this page on the 3rd of Februari at 5.30pm.
```

2021-01-12 11:12 UTC, th3tard1sparadox commented on website/pages/git_en.md
> +The 3rd of February 17:30-19:00 LiTHe-kod will be hosting
```suggestion
The 3rd of February 5.30pm to 7.00pm LiTHe-kod will be hosting
```

2021-01-12 11:12 UTC, th3tard1sparadox commented on website/pages/git_se.md
> +Dags att vässa ditt CV, skaffa kompetenser som bara fortsätter att ge och ha en
```suggestion
Dags att vässa ditt CV, skaffa användbara kompetenser och ha en
```

2021-01-13 01:10 UTC, sornas commented on website/pages/git_en.md
> +a git workshop on Zoom! To get there, simple visit this page on the 3rd of februari at 17:30.
February med stort F

2021-01-13 01:10 UTC, sornas commented on website/pages/git_en.md
> +to answer any question you may have.
```suggestion
to answer any questions you may have.
```

2021-01-13 01:10 UTC, sornas commented on website/pages/git_se.md
> +trevlig kväll med LiTHe-kod! Workshoppen lär ut git på ett interaktivt sätt
```suggestion
trevlig kväll med LiTHe kod! Workshoppen lär ut git på ett interaktivt sätt
```

2021-01-14 11:52 UTC, EMattfolk approved these changes

2021-01-14 12:08 UTC, sornas commented on website/pages/git_en.md
> +The workshop will teach git in an interactive manner, that is
```suggestion
The workshop will teach git in an interactive manner that is
```

2021-01-14 12:08 UTC, sornas commented on website/pages/git_en.md
> +The 3rd of February 5:30pm to 7:00pm LiTHe-kod will be hosting
```suggestion
The 3rd of February from 5:30pm to 7:00pm LiTHe kod will be hosting
```

2021-01-14 12:08 UTC, sornas commented on website/pages/git_en.md
> +You will be redirected using the magic of the internet and arrive at a stimulating Zoom-meeting.
```suggestion
You will be redirected using the magic of the internet and arrive at a stimulating Zoom meeting.
```

2021-01-14 12:08 UTC, sornas commented on website/pages/git_se.md
> +Bokmärk denna sida och skriv ner datumet i din kalender! Ses där.
```suggestion
Bokmärk denna sida och skriv ner datumet i din kalender! Ses där!
```

2021-01-14 12:08 UTC, sornas commented on website/pages/git_se.md
> +Den 3e februari kl 17:30-19:00 kommer LiTHe-kod att hålla i en git-workshop över Zoom!
```suggestion
Den 3e februari 17:30-19:00 kommer LiTHe-kod att hålla i en git-workshop över Zoom!
```

2021-01-14 12:08 UTC, sornas commented on website/pages/git_se.md
> +För att komma dit: gå till denna sida på onsdagen den 3e februari kl 17:30. Du kommer
```suggestion
För att komma dit: gå till denna sida på onsdagen den 3e februari kl. 17:30. Du kommer
```

2021-01-14 12:08 UTC, sornas commented on website/pages/git_se.md
> +den interaktiva delen av workshoppen där vi kommer ge ut "git-uppgifter" som ni
```suggestion
den interaktiva delen av workshoppen där vi ger ut "git-uppgifter" som ni
```

2021-01-14 12:13 UTC, sornas approved these changes

2021-01-14 12:14 UTC, merged