Spring game jam2021
lithekod/site-v2 pull request #59
Opened 2021-04-23 12:58 UTC by JesperTingvall

- Schema för Spring Game Jam 2021
- Mera historia & tools

2021-04-24 10:11 UTC, sornas approved these changes

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_en.md
> +- [Simplygon (3D-modell optimization)](https://www.simplygon.com/)
```suggestion
- [Simplygon (3D-model optimization)](https://www.simplygon.com/)
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +*18:00 7:e Maj - 19:00 9:e Maj*
```suggestion
*18:00 7:e maj - 19:00 9:e maj*
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +- [Facebook event](https://www.facebook.com/events/718957842117923)
```suggestion
- [Discordserver](https://discord.gg/eHgXYMS)
- [Itch.io-jam](https://itch.io/jam/spring-game-jam-2021)
- [Facebook-event](https://www.facebook.com/events/718957842117923)
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +- 18.00 - Intro stream
```suggestion
- 18.00 - Intro-stream
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +**Fredag Maj 7e:**
```suggestion
**Fredag 7:e maj:**
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +**Lördag Maj 8e:**
```suggestion
**Lördag 8:e maj:**
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +**Söndag Maj 9e:**
```suggestion
**Söndag 9:e maj:**
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +- 22:00 - Night-chill (Optional)
```suggestion
- 22:00 - Night-chill (frivilligt)
```

2021-04-24 10:11 UTC, sornas commented on website/pages/gamejam_se.md
> +- 22:00 - Night-chill (Optional)
Men är inte allt frivilligt egentligen? Det kanske finns ett bättre ord här än optional/frivilligt.

2021-04-25 17:13 UTC, rorro requested changes

2021-04-25 17:13 UTC, rorro commented on website/pages/gamejam_en.md
> +All events takes place on the LiU Game Jam Discord.  Times are given in Central European Summer Time (CEST) i.e. UTC+2.
```suggestion
All events take place on the LiU Game Jam Discord.  Times are given in Central European Summer Time (CEST) i.e. UTC+2.
```

2021-04-27 18:52 UTC, merged